import AppKit
import SwiftUI
import Combine

final class ResultPanel {
    private var panel: FloatingPanel?
    private var hostingController: NSHostingController<PopupView>?
    private var globalKeyMonitor: Any?
    private var localKeyMonitor: Any?
    private var clickMonitor: Any?

    /// True once the panel has been made key — happens when the first result
    /// arrives. After that, Return is captured locally and *not* sent to the
    /// source app (which would otherwise insert a newline before Replace
    /// fires on the now-modified text).
    private var isKeyFocused = false
    private let state: PopupState
    private var sizeCancellable: AnyCancellable?

    /// Cached position for repositioning on content resize.
    private var cachedSelectionRect: NSRect = .zero

    /// The mode ID currently being generated by the LLM.
    private var pendingModeId: UUID?

    /// In-flight stream for the currently-pending generation, so it can be
    /// cancelled when the user dismisses the panel or starts a new mode.
    private var activeStream: LLMService.StreamHandle?

    init(modes: [RewriteMode]) {
        self.state = PopupState(modes: modes)
    }

    func show(
        near selectionRect: NSRect,
        initialMode: RewriteMode,
        onModeSelected: @escaping (RewriteMode) -> Void,
        onReplace: @escaping (String) -> Void,
        onCopy: @escaping (String) -> Void
    ) {
        state.selectedModeId = initialMode.id
        state.modePhases[initialMode.id] = .loading
        state.loadingStartTimes[initialMode.id] = Date()
        pendingModeId = initialMode.id

        state.onModeSelected = { [weak self] mode in
            guard let self else { return }
            self.state.selectedModeId = mode.id
            if self.state.modePhases[mode.id] == nil {
                self.state.modePhases[mode.id] = .loading
                self.state.loadingStartTimes[mode.id] = Date()
                self.pendingModeId = mode.id
                onModeSelected(mode)
            }
        }
        state.onRegenerate = { [weak self] in
            guard let self, let modeId = self.state.selectedModeId else { return }
            guard let mode = self.state.modes.first(where: { $0.id == modeId }) else { return }
            self.state.modePhases[modeId] = .loading
            self.state.loadingStartTimes[modeId] = Date()
            self.pendingModeId = modeId
            self.resizePanel()
            onModeSelected(mode)
        }
        state.onReplace = { [weak self] text in
            self?.close()
            onReplace(text)
        }
        state.onCopy = { [weak self] text in
            self?.close()
            onCopy(text)
        }
        state.onCancel = { [weak self] in
            self?.close()
        }

        cachedSelectionRect = selectionRect
        showPanel(at: selectionRect)
    }

    func updateResult(_ text: String, modelName: String? = nil) {
        DispatchQueue.main.async {
            guard let modeId = self.pendingModeId else { return }
            let metadata = self.buildMetadata(for: modeId, modelName: modelName, tokenCount: nil)
            self.state.modePhases[modeId] = .result(text, metadata)
            self.state.loadingStartTimes[modeId] = nil
            self.state.streamingTokenCounts[modeId] = nil
            self.pendingModeId = nil
            self.resizePanel()
            self.acquireKeyFocus()
        }
    }

    /// Append a streaming chunk to the current mode's result. First chunk
    /// transitions the phase from `.loading` to `.streaming`; subsequent
    /// chunks grow the text in place.
    func appendChunk(_ chunk: String, modelName: String) {
        DispatchQueue.main.async {
            guard let modeId = self.pendingModeId else { return }

            let prior: String
            if case .streaming(let existing, _) = self.state.modePhases[modeId] {
                prior = existing
            } else {
                prior = ""
            }
            let newText = prior + chunk

            // chunks-as-tokens approximation; llama.cpp's Swift API yields
            // one token per chunk.
            let count = (self.state.streamingTokenCounts[modeId] ?? 0) + 1
            self.state.streamingTokenCounts[modeId] = count

            let metadata = self.buildMetadata(
                for: modeId,
                modelName: modelName,
                tokenCount: count
            ) ?? ResultMetadata(modelName: modelName, durationMs: 0, tokensPerSecond: 0)

            self.state.modePhases[modeId] = .streaming(newText, metadata)
            self.resizePanel()
        }
    }

    /// Mark the streaming phase as complete. Promotes the current `.streaming`
    /// text to `.result`, freezing the final metadata.
    func completeStream(modelName: String) {
        DispatchQueue.main.async {
            guard let modeId = self.pendingModeId else { return }

            let finalText: String
            if case .streaming(let text, _) = self.state.modePhases[modeId] {
                finalText = text.trimmingCharacters(in: .whitespacesAndNewlines)
            } else {
                return
            }
            let count = self.state.streamingTokenCounts[modeId]
            let metadata = self.buildMetadata(
                for: modeId,
                modelName: modelName,
                tokenCount: count
            )

            self.state.modePhases[modeId] = .result(finalText, metadata)
            self.state.loadingStartTimes[modeId] = nil
            self.state.streamingTokenCounts[modeId] = nil
            self.pendingModeId = nil
            self.resizePanel()
            self.acquireKeyFocus()
        }
    }

    /// Pull keyboard focus into the panel so Return / ⌘R / ⌘C are captured
    /// locally and don't bleed into the source app. The non-activating panel
    /// doesn't pull the whole app foreground — only key focus shifts.
    private func acquireKeyFocus() {
        guard let panel, !isKeyFocused else { return }
        panel.makeKey()
        isKeyFocused = true
    }

    func updateError(_ message: String) {
        DispatchQueue.main.async {
            guard let modeId = self.pendingModeId else { return }
            self.state.modePhases[modeId] = .error(message)
            self.state.loadingStartTimes[modeId] = nil
            self.pendingModeId = nil
            self.resizePanel()
        }
    }

    private func buildMetadata(
        for modeId: UUID,
        modelName: String?,
        tokenCount: Int?
    ) -> ResultMetadata? {
        guard let modelName, !modelName.isEmpty else { return nil }
        let elapsedMs: Int
        let elapsedSec: Double
        if let start = state.loadingStartTimes[modeId] {
            let interval = Date().timeIntervalSince(start)
            elapsedMs = Int(interval * 1000)
            elapsedSec = interval
        } else {
            elapsedMs = 0
            elapsedSec = 0
        }
        let tps: Double
        if let tokenCount, elapsedSec > 0 {
            tps = Double(tokenCount) / elapsedSec
        } else {
            tps = 0
        }
        return ResultMetadata(modelName: modelName, durationMs: elapsedMs, tokensPerSecond: tps)
    }

    private func showPanel(at selectionRect: NSRect) {
        let view = PopupView(state: state)
        let hosting = NSHostingController(rootView: view)
        hostingController = hosting

        let wrapper = FirstMouseView()
        let hostingView = hosting.view
        wrapper.addSubview(hostingView)
        hostingView.translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([
            hostingView.topAnchor.constraint(equalTo: wrapper.topAnchor),
            hostingView.bottomAnchor.constraint(equalTo: wrapper.bottomAnchor),
            hostingView.leadingAnchor.constraint(equalTo: wrapper.leadingAnchor),
            hostingView.trailingAnchor.constraint(equalTo: wrapper.trailingAnchor),
        ])

        // Compute initial content size.
        hosting.view.layoutSubtreeIfNeeded()
        let fittingSize = hosting.view.fittingSize
        let panelSize = NSSize(
            width: max(fittingSize.width, 340),
            height: max(fittingSize.height, 60)
        )

        // Position below the selection rect.
        let origin = panelOrigin(selectionRect: selectionRect, panelSize: panelSize)

        let floatingPanel = FloatingPanel(
            contentRect: NSRect(origin: origin, size: panelSize)
        )
        floatingPanel.contentView = wrapper
        floatingPanel.orderFront(nil)
        panel = floatingPanel

        installMonitors()
    }

    /// Recompute content size and resize the panel in place.
    private func resizePanel() {
        guard let panel, let hostingController else { return }
        hostingController.view.layoutSubtreeIfNeeded()
        let fittingSize = hostingController.view.fittingSize
        let newSize = NSSize(
            width: max(fittingSize.width, 340),
            height: max(fittingSize.height, 60)
        )
        let origin = panelOrigin(selectionRect: cachedSelectionRect, panelSize: newSize)
        panel.setFrame(NSRect(origin: origin, size: newSize), display: true, animate: false)
    }

    private func panelOrigin(selectionRect: NSRect, panelSize: NSSize) -> NSPoint {
        var origin: NSPoint
        if selectionRect.width > 0 && selectionRect.height > 0 {
            origin = NSPoint(
                x: selectionRect.origin.x,
                y: selectionRect.origin.y - panelSize.height - 4
            )
        } else if selectionRect.origin.x != 0 || selectionRect.origin.y != 0 {
            origin = NSPoint(
                x: selectionRect.origin.x - panelSize.width / 2,
                y: selectionRect.origin.y - panelSize.height - 4
            )
        } else {
            // Fallback: use current mouse position.
            let mouse = NSEvent.mouseLocation
            origin = NSPoint(
                x: mouse.x - panelSize.width / 2,
                y: mouse.y - panelSize.height - 4
            )
        }

        // Clamp to visible screen bounds so the panel is never off-screen.
        if let screen = NSScreen.main ?? NSScreen.screens.first {
            let visibleFrame = screen.visibleFrame
            origin.x = max(visibleFrame.minX, min(origin.x, visibleFrame.maxX - panelSize.width))
            origin.y = max(visibleFrame.minY, min(origin.y, visibleFrame.maxY - panelSize.height))
        }

        return origin
    }

    private func installMonitors() {
        removeMonitors()

        // Local monitor: fires when our panel has key focus. Returning nil
        // *consumes* the event so the source app never sees it — critical
        // for Return (would otherwise insert a newline) and for ⌘C / ⌘R.
        localKeyMonitor = NSEvent.addLocalMonitorForEvents(matching: .keyDown) { [weak self] event in
            guard let self else { return event }
            return self.handleKey(event) ? nil : event
        }

        // Global monitor: fires when key focus is in the source app. Used
        // before the panel becomes key (i.e. during the loading/streaming
        // phase). Cannot consume events — source app still receives them —
        // so we only catch Esc here. Return/⌘R/⌘C are intentionally not
        // handled globally; we wait until the panel has focus.
        globalKeyMonitor = NSEvent.addGlobalMonitorForEvents(matching: .keyDown) { [weak self] event in
            guard let self else { return }
            if event.keyCode == 53 { // Esc
                DispatchQueue.main.async { self.close() }
            }
        }

        clickMonitor = NSEvent.addGlobalMonitorForEvents(
            matching: [.leftMouseDown, .rightMouseDown]
        ) { [weak self] event in
            guard let self, let panel = self.panel else { return }
            // Convert to screen coordinates.
            let screenLoc: NSPoint
            if let eventWindow = event.window {
                screenLoc = eventWindow.convertToScreen(
                    NSRect(origin: event.locationInWindow, size: .zero)
                ).origin
            } else {
                screenLoc = event.locationInWindow
            }
            if !panel.frame.contains(screenLoc) {
                DispatchQueue.main.async { self.close() }
            }
        }
    }

    /// Handle a key event from either monitor. Returns true if we acted on it
    /// (caller should suppress the event).
    private func handleKey(_ event: NSEvent) -> Bool {
        let isCmd = event.modifierFlags.contains(.command)

        // Esc — dismiss
        if event.keyCode == 53 {
            DispatchQueue.main.async { self.close() }
            return true
        }
        // Return (36) or numpad Enter (76) — replace, only when result is ready
        if event.keyCode == 36 || event.keyCode == 76 {
            if case .result(let text, _) = self.state.currentPhase {
                DispatchQueue.main.async { self.state.onReplace?(text) }
                return true
            }
            return false
        }
        // ⌘R — regenerate (only after result is ready)
        if isCmd && event.keyCode == 15 {
            if case .result = self.state.currentPhase {
                DispatchQueue.main.async { self.state.onRegenerate?() }
                return true
            }
            return false
        }
        // ⌘C — copy (only after result is ready)
        if isCmd && event.keyCode == 8 {
            if case .result(let text, _) = self.state.currentPhase {
                DispatchQueue.main.async { self.state.onCopy?(text) }
                return true
            }
            return false
        }
        return false
    }

    /// Replace the stream handle for the in-flight generation. The previous
    /// handle, if any, is cancelled so we don't leak generators.
    func setActiveStream(_ handle: LLMService.StreamHandle?) {
        activeStream?.cancel()
        activeStream = handle
    }

    func close() {
        activeStream?.cancel()
        activeStream = nil
        removeMonitors()
        sizeCancellable = nil
        hostingController = nil
        panel?.orderOut(nil)
        panel = nil
    }

    private func removeMonitors() {
        if let monitor = localKeyMonitor {
            NSEvent.removeMonitor(monitor)
            localKeyMonitor = nil
        }
        if let monitor = globalKeyMonitor {
            NSEvent.removeMonitor(monitor)
            globalKeyMonitor = nil
        }
        if let monitor = clickMonitor {
            NSEvent.removeMonitor(monitor)
            clickMonitor = nil
        }
    }
}

/// NSView subclass that accepts first-mouse clicks so that buttons inside
/// a non-activating panel work on the first click (macOS < 15 requirement).
final class FirstMouseView: NSView {
    override func acceptsFirstMouse(for event: NSEvent?) -> Bool { true }
}
