import AppKit
import SwiftUI
import Combine

final class ResultPanel {
    private var panel: FloatingPanel?
    private var hostingController: NSHostingController<PopupView>?
    private var keyMonitor: Any?
    private var clickMonitor: Any?
    private let state: PopupState
    private var sizeCancellable: AnyCancellable?

    /// Cached position for repositioning on content resize.
    private var cachedSelectionRect: NSRect = .zero

    /// The mode ID currently being generated by the LLM.
    private var pendingModeId: UUID?

    init(modes: [RewriteMode]) {
        self.state = PopupState(modes: modes)
    }

    func show(
        near selectionRect: NSRect,
        initialMode: RewriteMode,
        onModeSelected: @escaping (RewriteMode) -> Void,
        onReplace: @escaping (String) -> Void,
        onCopy: @escaping (String) -> Void
    ) {
        state.selectedModeId = initialMode.id
        state.modePhases[initialMode.id] = .loading
        pendingModeId = initialMode.id

        state.onModeSelected = { [weak self] mode in
            guard let self else { return }
            self.state.selectedModeId = mode.id
            if self.state.modePhases[mode.id] == nil {
                self.state.modePhases[mode.id] = .loading
                self.pendingModeId = mode.id
                onModeSelected(mode)
            }
        }
        state.onReplace = { [weak self] text in
            self?.close()
            onReplace(text)
        }
        state.onCopy = { [weak self] text in
            self?.close()
            onCopy(text)
        }
        state.onCancel = { [weak self] in
            self?.close()
        }

        cachedSelectionRect = selectionRect
        showPanel(at: selectionRect)
    }

    func updateResult(_ text: String) {
        DispatchQueue.main.async {
            guard let modeId = self.pendingModeId else { return }
            self.state.modePhases[modeId] = .result(text)
            self.pendingModeId = nil
            self.resizePanel()
        }
    }

    func updateError(_ message: String) {
        DispatchQueue.main.async {
            guard let modeId = self.pendingModeId else { return }
            self.state.modePhases[modeId] = .error(message)
            self.pendingModeId = nil
            self.resizePanel()
        }
    }

    private func showPanel(at selectionRect: NSRect) {
        let view = PopupView(state: state)
        let hosting = NSHostingController(rootView: view)
        hostingController = hosting

        let wrapper = FirstMouseView()
        let hostingView = hosting.view
        wrapper.addSubview(hostingView)
        hostingView.translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([
            hostingView.topAnchor.constraint(equalTo: wrapper.topAnchor),
            hostingView.bottomAnchor.constraint(equalTo: wrapper.bottomAnchor),
            hostingView.leadingAnchor.constraint(equalTo: wrapper.leadingAnchor),
            hostingView.trailingAnchor.constraint(equalTo: wrapper.trailingAnchor),
        ])

        // Compute initial content size.
        hosting.view.layoutSubtreeIfNeeded()
        let fittingSize = hosting.view.fittingSize
        let panelSize = NSSize(
            width: max(fittingSize.width, 340),
            height: max(fittingSize.height, 60)
        )

        // Position below the selection rect.
        let origin = panelOrigin(selectionRect: selectionRect, panelSize: panelSize)

        let floatingPanel = FloatingPanel(
            contentRect: NSRect(origin: origin, size: panelSize)
        )
        floatingPanel.contentView = wrapper
        floatingPanel.orderFront(nil)
        panel = floatingPanel

        installMonitors()
    }

    /// Recompute content size and resize the panel in place.
    private func resizePanel() {
        guard let panel, let hostingController else { return }
        hostingController.view.layoutSubtreeIfNeeded()
        let fittingSize = hostingController.view.fittingSize
        let newSize = NSSize(
            width: max(fittingSize.width, 340),
            height: max(fittingSize.height, 60)
        )
        let origin = panelOrigin(selectionRect: cachedSelectionRect, panelSize: newSize)
        panel.setFrame(NSRect(origin: origin, size: newSize), display: true, animate: false)
    }

    private func panelOrigin(selectionRect: NSRect, panelSize: NSSize) -> NSPoint {
        var origin: NSPoint
        if selectionRect.width > 0 && selectionRect.height > 0 {
            origin = NSPoint(
                x: selectionRect.origin.x,
                y: selectionRect.origin.y - panelSize.height - 4
            )
        } else if selectionRect.origin.x != 0 || selectionRect.origin.y != 0 {
            origin = NSPoint(
                x: selectionRect.origin.x - panelSize.width / 2,
                y: selectionRect.origin.y - panelSize.height - 4
            )
        } else {
            // Fallback: use current mouse position.
            let mouse = NSEvent.mouseLocation
            origin = NSPoint(
                x: mouse.x - panelSize.width / 2,
                y: mouse.y - panelSize.height - 4
            )
        }

        // Clamp to visible screen bounds so the panel is never off-screen.
        if let screen = NSScreen.main ?? NSScreen.screens.first {
            let visibleFrame = screen.visibleFrame
            origin.x = max(visibleFrame.minX, min(origin.x, visibleFrame.maxX - panelSize.width))
            origin.y = max(visibleFrame.minY, min(origin.y, visibleFrame.maxY - panelSize.height))
        }

        return origin
    }

    private func installMonitors() {
        removeMonitors()

        // Global key monitor so we capture keystrokes even though our panel
        // is non-activating and the source app has focus.
        keyMonitor = NSEvent.addGlobalMonitorForEvents(matching: .keyDown) { [weak self] event in
            guard let self else { return }
            if event.keyCode == 53 { // Escape
                DispatchQueue.main.async { self.close() }
            }
            if event.keyCode == 36 { // Return
                DispatchQueue.main.async {
                    if case .result(let text) = self.state.currentPhase {
                        self.state.onReplace?(text)
                    }
                }
            }
        }

        clickMonitor = NSEvent.addGlobalMonitorForEvents(
            matching: [.leftMouseDown, .rightMouseDown]
        ) { [weak self] event in
            guard let self, let panel = self.panel else { return }
            // Convert to screen coordinates.
            let screenLoc: NSPoint
            if let eventWindow = event.window {
                screenLoc = eventWindow.convertToScreen(
                    NSRect(origin: event.locationInWindow, size: .zero)
                ).origin
            } else {
                screenLoc = event.locationInWindow
            }
            if !panel.frame.contains(screenLoc) {
                DispatchQueue.main.async { self.close() }
            }
        }
    }

    func close() {
        removeMonitors()
        sizeCancellable = nil
        hostingController = nil
        panel?.orderOut(nil)
        panel = nil
    }

    private func removeMonitors() {
        if let monitor = keyMonitor {
            NSEvent.removeMonitor(monitor)
            keyMonitor = nil
        }
        if let monitor = clickMonitor {
            NSEvent.removeMonitor(monitor)
            clickMonitor = nil
        }
    }
}

/// NSView subclass that accepts first-mouse clicks so that buttons inside
/// a non-activating panel work on the first click (macOS < 15 requirement).
final class FirstMouseView: NSView {
    override func acceptsFirstMouse(for event: NSEvent?) -> Bool { true }
}
